### ISSUE TITLE
Draft talking points for 11/17 TTS Town Hall

### ISSUE THREAD

**Issue by alexpandel** [18F/public-benefits-studio#8]
**Why:** to help wider TTS understand what the Studio is about and what's been happening with it thus far (and to plug future hiring!)

**Definition of done:**
- [ ] we've drafted talking points to fill a 2-minute opening (likely pulling from #2 )
- [ ] we've shared those talking points with Ashley for input & feedback

**Comment by amyashida** [comment]
I will turn this into slides and we can share the doc as follow up
